name: Dev Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: chmod +x gradlew

      - name: Set up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Get current dev build number
        id: dev-build
        run: |
          cd .github/devbuilds
          npm install
          node get_number.js >> $GITHUB_OUTPUT

      - name: Build
        run: ./gradlew build -Pcommit=${{ github.sha }} -Pdevbuild=${{ steps.dev-build.outputs.number }}

      # 新增上传工件步骤
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dev-build-${{ steps.dev-build.outputs.number }}
          path: |
            *
          retention-days: 1  # 保存工件的天数
